apiVersion: v1
kind: Secret
metadata:
  name: {{ include "temporal.fullname" . }}-db
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.database.user | quote }}
  password: {{ .Values.database.password | quote }}

