apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.fullname" . }}
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "temporal.selectorLabels" . | nindent 4 }}
  ports:
    - name: frontend
      port: {{ .Values.service.ports.frontend }}
      targetPort: frontend
      protocol: TCP
    {{- if .Values.ui.enabled }}
    - name: ui
      port: {{ .Values.service.ports.ui }}
      targetPort: ui
      protocol: TCP
    {{- end }}


