{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "temporal.fullname" . }}-ui
  labels:
    {{- include "temporal.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "temporal.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
  template:
    metadata:
      labels:
        {{- include "temporal.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      containers:
        - name: ui
          image: {{ printf "%s:%s" .Values.ui.image.repository .Values.ui.image.tag }}
          ports:
            - name: ui
              containerPort: {{ .Values.ui.containerPort }}
          env:
            - name: TEMPORAL_ADDRESS
              value: {{ printf "%s:%d" (include "temporal.fullname" .) .Values.service.ports.frontend | quote }}
            - name: TEMPORAL_CORS_ORIGINS
              value: "*"
            - name: TEMPORAL_PERMIT_WRITE_API
              value: "true"
{{- end }}

