{{- if .Values.stack.api }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sbs.fullname" . }}-api
  labels:
    {{- include "sbs.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.stack.api.service.type }}
  selector:
    {{- include "sbs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.stack.api.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}


